{{ if .Values.clusterIssuer.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.name }}
spec:
  acme:
    email: {{ .Values.clusterIssuer.email }}
    {{ if .Values.clusterIssuer.staging }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
    {{ else }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    {{ end }}
    solvers:
      - dns01:
          webhook:
            groupName: {{ .Values.groupName }}
            solverName: dnspod
            config:
              secretId: {{ .Values.clusterIssuer.secretId }}
              ttl: {{ .Values.clusterIssuer.ttl }}
              secretKeyRef:
                key: secretKey
                name: cert-manager-webhook-dnspod-secret
{{ end }}
