{{- if .Values.clusterIssuer.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dnspod-webhook.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "dnspod-webhook.name" . }}
    chart: {{ include "dnspod-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  secretKey: {{ required ".Values.clusterIssuer.secretKey is required" .Values.clusterIssuer.secretKey | b64enc | quote }}
{{- end }}