name: DEPLOY

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Publish
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: jmploop/cert-manager-webhook-dnspod
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
